### ISSUE TITLE
小学生に対して行う認識率テストのデモアプリの作成準備

### ISSUE THREAD

**Issue by oitsmalab** [smalab/VR_Input#10]
- 子供にしゃべらせる言葉のリスト（会話風になるように）
- リストの実装

**Comment by oitsmalab** [comment]
８ポイント想定。

**Comment by yanoty3d** [comment]
- [x] 言わせたい単語の文字を表示させる
- [x] 言わせたい文字が言われたかチェックできるようにする
- [x] 正解、間違いで反応を変える
- [x] 子供にしゃべらせたい単語、文章のリスト。２０くらい。一つの会話のような流れになるよう、シナリオを作る。

**Comment by oitsmalab** [comment]
@6041fad4184f3baa419d9a897805355710dd8a3a
シナリオ完成
