### ISSUE TITLE
小学生に対して行う認識率テストのデモアプリの作成

### ISSUE THREAD

**Issue by oitsmalab** [smalab/VR_Input#11]
すでに用意したシナリオを使う
 特殊効果（認識されたときに音を出す、絵を出すなど）の実装

**Comment by oitsmalab** [comment]
１３ポイントを想定。

**Comment by oitsmalab** [comment]
@ f662e08863f6ef66f5849d10bfe75b5811e2e8d8
都道府県の認識成功

**Comment by yanoty3d** [comment]
ボタンを押しているときだけ、認識できるようにする。
