### ISSUE TITLE
RealSenseSDK　で認識　

### ISSUE THREAD

**Issue by yanoty3d** [smalab/VR_Input#12]
https://software.intel.com/sites/landingpage/realsense/jp/

**Comment by yanoty3d** [comment]
http://www.naturalsoftware.jp/entry/2015/07/28/100225　にあるサンプルプロジェクトを利用して、Unityで音声認識を実行する。使えるマイクが限られるので注意。

https://drive.google.com/file/d/0B1IUVPG3GzFARUlLZ0tOeFFGakk/view?usp=sharing　こちらも利用可能

**Comment by oitsmalab** [comment]
音声認識OK。喋った言葉を画面に表示させることまで完了。

**Comment by yanoty3d** [comment]
上記のコードはこちら　@0b51f013b176f86bb70f0ec057b606ade91daef7
