### ISSUE TITLE
単語の問題１０問

### ISSUE THREAD

**Issue by yanoty3d** [smalab/VR_Input#14]
動物　８
食べ物　４
飲み物　３
単語を決定して、認識できるようにする

一緒に使う紙教材を用意しておく

**Comment by oitsmalab** [comment]
@ 9ca08ae1cac3070b100009df5ae4f4919e932fd6
動物8単語　テストまで終了

**Comment by oitsmalab** [comment]
@ 286ea01bebd467062138d5a7b30bb33d886f2694
食べ物7単語　テストまで終了

**Comment by oitsmalab** [comment]
@ 725881f9696233242b2e95aca9ee61ba48c537dd
飲み物4単語　登録終了

**Comment by oitsmalab** [comment]
紙教材を作成し、作業終了とする
