### ISSUE TITLE
合成音声ソフトを使い、音声データを作る

### ISSUE THREAD

**Issue by oitsmalab** [smalab/VR_Input#21]
音声合成ができるソフトを探し、それらから、子供、大人の声データと同じアルファベット、単語の発音を録音する。
- [x] 女性の声で録音したものを、google driveに保存する。
- [x] 男性の声で録音したものを、google driveに保存する。 
- [x] 子供の声で録音したものを、google driveに保存する。
- [x] 音声の出典をメモし、テキストファイルとして残しておく。

**Comment by oitsmalab** [comment]
@ c84fa29b95022f183e212fb41846bd6e3ce0c579
子供の声で録音したもののみ、達成

**Comment by yanoty3d** [comment]
音を聞いてみましたが、Y,Zのところが「わいずいー」と繋がっているなど、問題点がいくつかあるようです。丁寧にチェックして、一つ一つの音がしっかり分かれて、正しく発音されるように作ってください。

**Comment by oitsmalab** [comment]
@ dfe1c091949053e3b9a1fbd7971b78c71af6b883
音声のつながりがあったため、修正しました。

**Comment by oitsmalab** [comment]
@ abd80fafe8234cd983acf7eacdd2de793cd5c47c
女性の合成音声　アルファベットのみ

**Comment by oitsmalab** [comment]
@ 5f118b8f99f7514212dd19071872074231ec4581
女性の合成音声すべて完了。[]にチェック済み

**Comment by oitsmalab** [comment]
@ 505e7d9b35fd2c0d0b7795f9b3d866c1e70ed9cc
男性の合成音声すべてgoogledriveにあげました。

**Comment by yanoty3d** [comment]
出典がわからなくなると卒論の時に困るので、どこのサイトのどの音を使ったのか、などの記録を残してください。

**Comment by oitsmalab** [comment]
音作成に使用したサイト、ソフト
・VOICEROID+月読アイ
・SofTalk
・AITalk(http://www.ai-j.jp/)
