### ISSUE TITLE
音声サンプルファイルを、juliusで読ませる

### ISSUE THREAD

**Issue by oitsmalab** [smalab/VR_Input#22]
マイク入力ではなく、mp3などのファイルを直接読ませて、juliusに認識させたい。
- [x] サンプルファイルの用意
- [x] サンプルファイルのjuliusでの認識
- [x] サンプルファイルをiPod Touchに入れ、マイク入力で認識。
- [x] 二つの結果の比較

**Comment by oitsmalab** [comment]
@ 34abcefb92407358197e622d10907400646f25d7
juliusを起動したと同時に指定した音声ファイルの音が流れるようになった。
音と音の間が短すぎるためか音声認識はされなかった。

**Comment by oitsmalab** [comment]
@ 45e45e279984e624f7fba7374f71d25100f8b0dc
前回の問題であった音声認識について、短い音データを作成することによって解決できると思われたが、解決されなかった。

**Comment by oitsmalab** [comment]
@ 45e45e279984e624f7fba7374f71d25100f8b0dc
前回の問題であった音声認識について、短い音データを作成することによって解決できると思われたが、解決されなかった。

**Comment by oitsmalab** [comment]
@ 45e45e279984e624f7fba7374f71d25100f8b0dc
前回の問題であった音声認識について、短い音データを作成することによって解決できると思われたが、解決されなかった。

**Comment by oitsmalab** [comment]
@ 45e45e279984e624f7fba7374f71d25100f8b0dc
前回の問題であった音声認識について、短い音データを作成することによって解決できると思われたが、解決されなかった。

**Comment by oitsmalab** [comment]
@ 45e45e279984e624f7fba7374f71d25100f8b0dc
前回の問題であった音声認識について、短い音データを作成することによって解決できると思われたが、解決されなかった。

**Comment by oitsmalab** [comment]
@ 45e45e279984e624f7fba7374f71d25100f8b0dc
前回の問題であった音声認識について、短い音データを作成することによって解決できると思われたが、解決されなかった。

**Comment by oitsmalab** [comment]
@ 45e45e279984e624f7fba7374f71d25100f8b0dc
前回の問題であった音声認識について、短い音データを作成することによって解決できると思われたが、解決されなかった。

**Comment by oitsmalab** [comment]
@ 45e45e279984e624f7fba7374f71d25100f8b0dc
音データを短くし、音声認識させたがうまくいかなかった

**Comment by yanoty3d** [comment]
iPodから直接流す方法も考える。マイクを使うか、マイク端子を使うか

**Comment by oitsmalab** [comment]
@ 1206fffd19264c02a107120928d9732cc6a629cd
iPodtouchでの音声認識を行うための前準備

**Comment by oitsmalab** [comment]
@ 0ace8b21dbb9c435f7f36a3160661dccd17c98c4
マイク入力をおこなったところ、アルファベットのM以外すべて誤認識された。
試しに私の声で行うと、試行回数は多いもののすべて認識された。

**Comment by oitsmalab** [comment]
@ a6168392cf28221b8997f4f7ba12dadcf2f994a0
試行回数を増やすため、音データを1音、1単語に区切った。@ 0ace8b2 で失敗したところを検証して改善していきたい。音データはGoogleDriveのマイドライブ＞卒研2015＞田端＞音データ＞1音、1単語　に格納している。
