### ISSUE TITLE
各種音声のアルファベットの発音をバラバラにする　

### ISSUE THREAD

**Issue by yanoty3d** [smalab/VR_Input#24]
各種(9種類）音声の、認識率の記録をとる準備として
- [x] A~Z迄について、バラバラに入力できるよう、音声ファイルを加工する。

**Comment by oitsmalab** [comment]
@ 0b8170266136a6bbca0d44d20f95b9f590b581b7
9種類のうち3種類(合成音声の月読アイ、男性、女性)のアルファベットを1音ごとに区切り、googledriveに保存しました。
マイドライブ＞卒研2015＞田端＞音データ　にそれぞれの名前のフォルダがあり、そこに格納してあります。

**Comment by oitsmalab** [comment]
@ 3ccd1274e0ceb551b6d1ec5d3d832acf06764ea9
9種類のうち9種類終了。残りの作業であった子供（女の子）の2つ目の音データの分割作業が終了。googledriveには保存せず、私の作業PCのデスクトップ＞子供音声＞alphabetにすべて保存した。
