### ISSUE TITLE
各種音声について、認識率をアルファベットごとに記録する

### ISSUE THREAD

**Issue by yanoty3d** [smalab/VR_Input#25]
- [x] A~Z迄について、各々認識されたかを○×で記録。
- [x] 少なくとも、3回は繰り返すこと。

**Comment by oitsmalab** [comment]
@ 62f01e7053c238394a98cb513a773c1cadeea385
月読アイの認識テスト終了。26文字の認識率の平均3.94％

**Comment by oitsmalab** [comment]
@ db508090380a0c578aee625220b97370e11304f5
合成音声（男性）の認識テスト終了。26文字の認識率の平均41.92％

**Comment by oitsmalab** [comment]
@ fea3b15486f8fbc387969483f469f086a41e1abe
合成音声（女性）の認識テスト終了。26文字の認識率の平均34.23％

**Comment by oitsmalab** [comment]
@ 189ef88f2355eb92c3a29151a9ce95c8af173cf8
大人音声（男性）の認識テスト終了。26文字の認識率の平均27.31％

**Comment by oitsmalab** [comment]
@ 5752822f9a1dad4ba1237ea1338389b8ac15f71f
大人音声（女性）の認識テスト終了。26文字の認識率の平均7.69％

**Comment by oitsmalab** [comment]
@ ba72a62c2fcb2736383efaaae8501ce629c1f160
子供音声（男の子１）の認識テスト終了。26文字の認識率の平均16.15％
