### ISSUE TITLE
月読アイの声をかえて、認識率を上げる

### ISSUE THREAD

**Issue by yanoty3d** [smalab/VR_Input#26]
速さ、音程、音量？をかえてみる
しゃべる内容も変えてみる
辞書の工夫
３０～５０％

文献も調べること(子供の何が問題か）

**Comment by oitsmalab** [comment]
@ 9cbcb1aad19bdb7c2e1a252983b434b8d5192e0f
速さ、音程、音量、話す内容（英単語）の音声データを作成した。

**Comment by oitsmalab** [comment]
@ dda908962d72fb1866e156d697f60c12370b6f47
動物英単語完了。飲食物英単語6/7完了。
動物英単語の最も認識率の良かったパラメータは速さ1/2の43％で、英単語は”cow”の76％であった。

**Comment by oitsmalab** [comment]
@ a38b41cfaeabdc6841b7088a22b4c47dbd105cbe
月読アイの英単語認識全項目完了。
飲食物英単語は全体的に認識が悪く、最も良いパラメータは音程変化の20％で、英単語は”hamburger”の48％であった。

**Comment by yanoty3d** [comment]
認識率が悪いものについては、デフォルト設定で50％認識率以下の場合にのみ、何と間違えるかを調べておく

**Comment by oitsmalab** [comment]
@ 669ad9c67d39ae2307637fcf08fac3e9ac18b4fc
月読アイ英単語認識50%未満再テスト終了。
cat(28%),cow(96%),giraffe(60%),bear(8%),monkey(16%),wolf(24%),tiger(0%),lion(16%),
hamburger(52%),water(20%),salmon(60%),meat(4%),candy(4%),fish(4%),yogurt(0%)となった。
テストに用いたシート（何と間違えたかも記載）は、卒研2015＞田端においてある
