### ISSUE TITLE
言語モデルがUnityでも使用できるかどうか確認する

### ISSUE THREAD

**Issue by oitsmalab** [smalab/VR_Input#4]
**DOD**
- [ ] Unity内で、Savantさんのプロジェクトと他サイトの言語モデルファイルを用いた認識を行う。

**Comment by oitsmalab** [comment]
http://tips.hecomi.com/entry/20120112/1326390200
上記のURLを確認し、言語モデルは何なのかを理解する。
次に、Unityでも同じようなモデルを実装できないか試す。

**Comment by oitsmalab** [comment]
編集すべき箇所が把握できたかもしれないので、スクリプトを編集。
.gramおよび.vocaファイルは凹みさんの記事のものを引用。
.jconfファイルはサンプルキットから引用する。

**Comment by yanoty3d** [comment]
estimate = 8に設定

**Comment by yanoty3d** [comment]
dfa, dictファイルをもってくる
http://tips.hecomi.com/entry/20120112/1326390200　方法の通り、
./bin/julius -C hmm_mono.jconf -gram kaden -input mic　で実行？

「UTF-8 で編集しているので charconv オプションを付ける必要はありません」？
