### ISSUE TITLE
Savantさんのオリジナルライブラリで認識できる英単語、句の種類を増やす

### ISSUE THREAD

**Issue by yanoty3d** [smalab/VR_Input#5]
SavantさんのJulius-Client-for-Unityのcommnd.htkdicだけを変更して、どこまで英語を認識できるか挑戦する。発音を書く際は、以下のことに気を付ける。

http://deg-nico.seesaa.net/article/304283044.html
https://mmdagent.wordpress.com/2013/02/01/kana-to-phone-mapping-in-recognition-dictionary/

「初音ミク」を登録する場合は
初音ミク h a ts u n e m i k u

記述ルールは、”登録したい単語+半角スペース+ローマ字読み”となります。

ただし、ローマ字読み（音素記号）の記述ルールは以下の通りです。

・基本は小文字のアルファベットを使う。
・母音と子音の間に半角スペースを入れる。
・「ん」は大文字の「N」。
・小さい「っ」は「q」で表す。
・伸ばす音は母音に「:(コロン)」を付ける。
　例　ハッピーシンセサイザ h a q p i: sh i N s e s a i z a
・発音に近い表記をする。
　例　「昨日」は「きのー」と表現し「k i n o:」と表記する。
・助詞の「は」「へ」は，それぞれ「w a」「e」と表記する。
・記述の例
　チェンジ ch e N j i
　終了 sh u: ry o:
　ウェーブファイル w e: b u f a i r u
　ジャンプ j a N p u

**Comment by oitsmalab** [comment]
目標１００単語

**Comment by oitsmalab** [comment]
@ddc3bbc2d59d244ab4654ec3749daf9a1925b827
約90単語登録
